# Do not edit this file.

source 'https://rubygems.org'

gem 'pry'
gem 'sinatra'
gem 'sinatra-contrib'

gem 'activesupport'

gem 'sinatra-flash'
gem 'sinatra-redirect-with-flash'

gem "minitest-rg"

gem "rake"